services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app
    networks:
      - transaction-network

  celery_worker:
    build: .
    command: celery -A tasks.celery_tasks worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - db
    volumes:
      - ./src:/app
    networks:
      - transaction-network

  celery_beat:
    build: .
    command: celery -A tasks.celery_tasks beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - db
    volumes:
      - ./src:/app
    networks:
      - transaction-network

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - transaction-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - transaction-network

volumes:
  postgres_data:
  redis_data:

networks:
  transaction-network:
    driver: bridge
